### ISSUE TITLE
Some items not being cached in db when using `.create`

### ISSUE THREAD

**Issue by waptik** [skoshx/pentagon#30]
So some few days ago, i made a report under one of my [bug report issue](https://github.com/skoshx/pentagon/issues/28#issuecomment-1637177489).  For some weird reasons, when i create new items using the `.create` method, some items are being and can retrieved alright whilst other can't
I'm using deno 1.35.1

The bug can be reproduce by cloning [this repo](https://github.com/waptik/test-deno-pentagon) and running `deno task start` from your terminal

**Comment by skoshx** [comment]
Thanks a lot for the reproduction, will be super busy until Friday, but on the weekend I will have time to look into this! Thanks for your patience :)

**Comment by waptik** [comment]
Alright, understood. I'll be waiting for your feedback on this issue when you become available

**Comment by skoshx** [comment]
@waptik 

Ok, basically the problem was because the `id` was generated by Zod's default schema, those didn't get taken into account when Pentagon internally creates keys to save the items by.

The latest commit fixed this problem, and your example repository works perfectly with the latest commit! I will create a release as this is quite a severe problem for a normal use-case.

Thanks a lot for opening this issue and creating the reproduction, this problem was quite subtle.🙌

**Comment by waptik** [comment]
> @waptik 
> 
> 
> 
> Ok, basically the problem was because the `id` was generated by Zod's default schema, those didn't get taken into account when Pentagon internally creates keys to save the items by.
> 
> 
> 
> The latest commit fixed this problem, and your example repository works perfectly with the latest commit! I will create a release as this is quite a severe problem for a normal use-case.
> 
> 
> 
> Thanks a lot for opening this issue and creating the reproduction, this problem was quite subtle.🙌

Oh I see. I thought it was an issue with my system. 
I'm glad you found the underlying issue and fixed it. 

I'll update my codebase with latest version and try it out. 

Thanks for taking your time to solve it
